### ISSUE TITLE
Help with old project, Marketplace down :(

### ISSUE THREAD

**Issue by jolimk** [blesta/gateway-2checkout#2]
Hey @abdyfranco, im sorry to use another git for this comment but I don't know how else to contact you. The marketplace for MacOSIFTTTControl is DOWN, and I want to check some old stuff that you have there please. Thank you very much! Great project!

**Comment by abdyfranco** [comment]
I have several other repositories in my personal profile where you could have created this issue. Not mean to be rude, but please don't create any more issues about my personal projects in any of the organizations I belong to on GitHub. ..and btw, the Marketplace is up again.
